# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family      JetBrains Mono Medium
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 13.0

#: Font size (in pts)

adjust_line_height  100%

#: Change the size of each character cell kitty renders. You can use
#: either numbers, which are interpreted as pixels or percentages
#: (number followed by %), which are interpreted as percentages of the
#: unmodified values. You can use negative pixels or percentages less
#: than 100% to reduce sizes (but this might cause rendering
#: artifacts).

background_opacity 0.8

#: Neutron theme

background            #1b1d22
foreground            #e6e8ee
cursor                #f6f6ec
selection_background  #2e353d
color0                #22252b
color8                #22252b
color1                #b53f36
color9                #b53f36
color2                #5ab977
color10               #5ab977
color3                #ddb566
color11               #ddb566
color4                #6a7b92
color12               #6a7b92
color5                #a3799d
color13               #a3799d
color6                #3f93a8
color14               #3f93a8
color7                #e6e8ee
color15               #ebedf2
selection_foreground  #1b1d22

sync_to_monitor yes

bell_on_tab "🔔"

draw_minimal_borders yes

macos_colorspace srgb



